# Generated by Django 2.0.7 on 2018-07-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180728_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Pizza Topping',
                'verbose_name_plural': 'Pizza Toppings',
            },
        ),
        migrations.AlterModelOptions(
            name='dinnerplatter',
            options={'verbose_name': 'Dinner Platter', 'verbose_name_plural': 'Dinner Platters'},
        ),
        migrations.AlterModelOptions(
            name='sizecategory',
            options={'verbose_name': 'Size', 'verbose_name_plural': 'Sizes'},
        ),
    ]
