# Generated by Django 2.0.7 on 2018-07-28 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_sub_subtopping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinnerplatter',
            old_name='category',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='size_category',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='pizza_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='sub',
            old_name='category',
            new_name='size',
        ),
    ]
