# Generated by Django 2.0.7 on 2018-07-29 23:16

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
    ]
