# Generated by Django 2.0.7 on 2018-07-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20180729_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.CharField(max_length=500),
        ),
    ]
