# Generated by Django 2.0.7 on 2018-07-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20180729_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
        migrations.AddField(
            model_name='cart',
            name='item_pasta',
            field=models.ManyToManyField(blank=True, related_name='carts', to='orders.Pasta'),
        ),
        migrations.AddField(
            model_name='cart',
            name='item_pizza',
            field=models.ManyToManyField(blank=True, related_name='carts', to='orders.Pizza'),
        ),
        migrations.AddField(
            model_name='cart',
            name='item_pizzatopping',
            field=models.ManyToManyField(blank=True, related_name='carts', to='orders.PizzaTopping'),
        ),
        migrations.AddField(
            model_name='cart',
            name='item_platter',
            field=models.ManyToManyField(blank=True, related_name='carts', to='orders.DinnerPlatter'),
        ),
        migrations.AddField(
            model_name='cart',
            name='item_salad',
            field=models.ManyToManyField(blank=True, related_name='carts', to='orders.Salad'),
        ),
        migrations.AddField(
            model_name='cart',
            name='item_sub',
            field=models.ManyToManyField(blank=True, related_name='carts', to='orders.Sub'),
        ),
        migrations.AddField(
            model_name='cart',
            name='item_subtopping',
            field=models.ManyToManyField(blank=True, related_name='carts', to='orders.SubTopping'),
        ),
    ]
