# Generated by Django 2.0.7 on 2018-07-29 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0013_auto_20180729_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveIntegerField()),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pasta', models.ManyToManyField(blank=True, related_name='orders', to='orders.Pasta')),
            ],
        ),
        migrations.AlterField(
            model_name='dinnerplatter',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dinnerplatters', to='orders.SizeCategory'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pizzas', to='orders.SizeCategory'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pizzas', to='orders.PizzaCategory'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subs', to='orders.SizeCategory'),
        ),
        migrations.AddField(
            model_name='order',
            name='pizza',
            field=models.ManyToManyField(blank=True, related_name='orders', to='orders.Pizza'),
        ),
        migrations.AddField(
            model_name='order',
            name='pizzatopping',
            field=models.ManyToManyField(blank=True, related_name='orders', to='orders.PizzaTopping'),
        ),
        migrations.AddField(
            model_name='order',
            name='platter',
            field=models.ManyToManyField(blank=True, related_name='orders', to='orders.DinnerPlatter'),
        ),
        migrations.AddField(
            model_name='order',
            name='salad',
            field=models.ManyToManyField(blank=True, related_name='orders', to='orders.Salad'),
        ),
        migrations.AddField(
            model_name='order',
            name='sub',
            field=models.ManyToManyField(blank=True, related_name='orders', to='orders.Sub'),
        ),
        migrations.AddField(
            model_name='order',
            name='subtopping',
            field=models.ManyToManyField(blank=True, related_name='orders', to='orders.SubTopping'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
