# Generated by Django 2.0.7 on 2018-07-30 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20180730_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastaCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('Cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Cart')),
                ('Pasta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Pasta')),
            ],
        ),
    ]
