# Generated by Django 2.0.7 on 2018-07-30 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20180730_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RP', 'Regular Pizza'), ('SP', 'Sicilian Pizza'), ('SUB', 'Sub'), ('SAL', 'Salad'), ('PAS', 'Pasta'), ('PLA', 'Dinner Platter'), ('PT', 'Pizza Topping'), ('ST', 'Sub Topping')], max_length=4)),
                ('name', models.CharField(max_length=200)),
                ('size', models.CharField(choices=[('SM', 'Small'), ('LG', 'Large')], max_length=2, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='pastacart',
            name='Cart',
        ),
        migrations.RemoveField(
            model_name='pastacart',
            name='Pasta',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='pasta',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='pizzatopping',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='platter',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='salad',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='subtopping',
        ),
        migrations.DeleteModel(
            name='PastaCart',
        ),
        migrations.AddField(
            model_name='cartentry',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Cart'),
        ),
        migrations.AddField(
            model_name='cartentry',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Menu'),
        ),
    ]
