# Generated by Django 2.0.7 on 2018-07-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20180730_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartentry',
            options={'verbose_name': 'Cart Entry', 'verbose_name_plural': 'Cart Entries'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='size',
            field=models.CharField(blank=True, choices=[('SM', 'Small'), ('LG', 'Large')], max_length=2, null=True),
        ),
    ]
