# Generated by Django 2.0.7 on 2018-07-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20180730_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('Regular Pizza', 'Regular Pizza'), ('Sicilian Pizza', 'Sicilian Pizza'), ('SUB', 'Sub'), ('SAL', 'Salad'), ('Pasta', 'Pasta'), ('PLA', 'Dinner Platter'), ('PT', 'Pizza Topping'), ('ST', 'Sub Topping')], max_length=4),
        ),
    ]
