# Generated by Django 2.0.7 on 2018-07-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20180730_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('REG', 'Regular Pizza'), ('SIC', 'Sicilian Pizza'), ('SUB', 'Sub'), ('SAL', 'Salad'), ('PAS', 'Pasta'), ('PLA', 'Dinner Platter'), ('PT', 'Pizza Topping'), ('ST', 'Sub Topping')], max_length=50),
        ),
    ]
