# Generated by Django 2.0.7 on 2018-07-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20180730_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinnerplatter',
            name='size',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='type',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='size',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pasta',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pizzatopping',
        ),
        migrations.RemoveField(
            model_name='order',
            name='platter',
        ),
        migrations.RemoveField(
            model_name='order',
            name='salad',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subtopping',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('COM', 'Complete')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('REG', 'Regular Pizza'), ('SIC', 'Sicilian Pizza'), ('SUB', 'Sub'), ('SAL', 'Salad'), ('PAS', 'Pasta'), ('PLA', 'Dinner Platter'), ('PT', 'Pizza Topping'), ('ST', 'Sub Topping')], max_length=5),
        ),
        migrations.DeleteModel(
            name='DinnerPlatter',
        ),
        migrations.DeleteModel(
            name='Pasta',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='PizzaCategory',
        ),
        migrations.DeleteModel(
            name='PizzaTopping',
        ),
        migrations.DeleteModel(
            name='Salad',
        ),
        migrations.DeleteModel(
            name='SizeCategory',
        ),
        migrations.DeleteModel(
            name='Sub',
        ),
        migrations.DeleteModel(
            name='SubTopping',
        ),
    ]
