# Generated by Django 2.0.7 on 2018-07-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20180730_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('COM', 'Complete')], max_length=3),
        ),
    ]
