# Generated by Django 2.0.7 on 2018-07-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20180730_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='size',
            field=models.CharField(blank=True, choices=[('Small', 'Small'), ('Large', 'Large')], max_length=6, null=True),
        ),
    ]
