# Generated by Django 2.0.7 on 2018-07-31 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20180731_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated',
        ),
    ]
