# Generated by Django 2.0.7 on 2018-08-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_auto_20180801_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('RegularPizza', 'Regular Pizza'), ('SicilianPizza', 'Sicilian Pizza'), ('Sub', 'Sub'), ('Salad', 'Salad'), ('Pasta', 'Pasta'), ('DinnerPlatter', 'Dinner Platter')], max_length=20),
        ),
    ]
