# Generated by Django 2.0.7 on 2018-08-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_auto_20180801_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopping',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=4),
        ),
    ]
