# Generated by Django 2.0.7 on 2018-08-01 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_subtopping_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizzatoppingentry',
            old_name='topping1',
            new_name='topping',
        ),
        migrations.RenameField(
            model_name='subtoppingentry',
            old_name='topping1',
            new_name='topping',
        ),
        migrations.RemoveField(
            model_name='pizzatoppingentry',
            name='topping2',
        ),
        migrations.RemoveField(
            model_name='pizzatoppingentry',
            name='topping3',
        ),
        migrations.RemoveField(
            model_name='subtoppingentry',
            name='topping2',
        ),
        migrations.RemoveField(
            model_name='subtoppingentry',
            name='topping3',
        ),
        migrations.RemoveField(
            model_name='subtoppingentry',
            name='topping4',
        ),
    ]
