# Generated by Django 2.0.7 on 2018-08-01 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_auto_20180801_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzatoppingentry',
            name='topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping', to='orders.PizzaTopping'),
        ),
        migrations.AlterField(
            model_name='subtoppingentry',
            name='topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping', to='orders.SubTopping'),
        ),
    ]
