# Generated by Django 2.0.7 on 2018-08-01 23:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_auto_20180801_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzatoppingentry',
            name='orderentry',
        ),
        migrations.RemoveField(
            model_name='subtoppingentry',
            name='orderentry',
        ),
        migrations.AddField(
            model_name='pizzatoppingentry',
            name='cartentry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.CartEntry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtoppingentry',
            name='cartentry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.CartEntry'),
            preserve_default=False,
        ),
    ]
