# Generated by Django 2.0.7 on 2018-08-01 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_auto_20180801_1927'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubToppingEntry',
            new_name='PizzaTopping_Entry',
        ),
        migrations.RenameModel(
            old_name='PizzaToppingEntry',
            new_name='SubTopping_Entry',
        ),
        migrations.AlterModelOptions(
            name='pizzatopping_entry',
            options={'verbose_name': 'Pizza Topping Entry', 'verbose_name_plural': 'Pizza Topping Entries'},
        ),
        migrations.AlterModelOptions(
            name='subtopping_entry',
            options={'verbose_name': 'Sub Topping Entry', 'verbose_name_plural': 'Sub Topping Entries'},
        ),
        migrations.AlterField(
            model_name='pizzatopping_entry',
            name='topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping', to='orders.PizzaTopping'),
        ),
        migrations.AlterField(
            model_name='subtopping_entry',
            name='topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping', to='orders.SubTopping'),
        ),
    ]
