# Generated by Django 2.0.7 on 2018-08-02 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_auto_20180801_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaTopping_OrderEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderentry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderEntry')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_topping', to='orders.PizzaTopping')),
            ],
            options={
                'verbose_name': 'Pizza Topping Order Entry',
                'verbose_name_plural': 'Pizza Topping Order Entries',
            },
        ),
        migrations.CreateModel(
            name='SubTopping_OrderEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderentry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderEntry')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_topping', to='orders.SubTopping')),
            ],
            options={
                'verbose_name': 'Sub Topping Order Entry',
                'verbose_name_plural': 'Sub Topping Order Entries',
            },
        ),
        migrations.AlterModelOptions(
            name='pizzatoppingentry',
            options={'verbose_name': 'Pizza Topping Cart Entry', 'verbose_name_plural': 'Pizza Topping Cart Entries'},
        ),
        migrations.AlterModelOptions(
            name='subtoppingentry',
            options={'verbose_name': 'Sub Topping Cart Entry', 'verbose_name_plural': 'Sub Topping Cart Entries'},
        ),
    ]
